### ISSUE TITLE
Email Field is case sensitive

### ISSUE THREAD

**Issue by one4many** [apragacz/django-rest-registration#123]
The email field seems to be case sensitive. So it allows to register different users with the same email address.
Example: _Email@host.com_, _email@host.com_, _email@host.COM_ are all treated as separate accounts which they should not.
Please fix.

**Comment by apragacz** [comment]
> Example: Email@host.com, email@host.com, email@host.COM are all treated as separate accounts which they should not.

According to RFCs,  Email@host.com and email@host.com are different addresses - only the domain part is case insensitive:
https://stackoverflow.com/questions/556090/how-do-i-upper-case-an-email-address

> Please fix.

EmailField behavior is defined by Django itself, and the issues with it have been already addressed:
https://code.djangoproject.com/ticket/17561
https://stackoverflow.com/questions/50895643/removing-case-sensitivity-from-email-in-django-login-form

EmailField used in serializer is defined by Django REST Framework.

Unfortunately due to lack of information I will have to close that one, unless you provide more specifics what is the actual issue. The preferred way to report a bug report is to use the template available here: https://github.com/apragacz/django-rest-registration/issues/new/choose
