### ISSUE TITLE
Switch to class-based views

### ISSUE THREAD

**Issue by peterthomassen** [apragacz/django-rest-registration#55]
Class-based views greatly simplify adding extra logic into views. I am therefore proposing to refactor the views into class-based views.

Here are some examples why this is useful, at least as far as the user registration view is concerned:

1.)
For user registration, I would like to record the client IP address. This is best done in the `register` view, by calling `serializer_class()` with an extra `context` argument, like `serializer_class(data=request.data, context={'request': request})`. This way, the serializer can access `self.context['request'].META.get('REMOTE_ADDR')` and populate a field on the model instance it creates.

As far as I can see, this is currently not possible, except by replacing the view by a copy of it and modifying it. This violates the DRY principle and is also detached from future upstream changes in this view.

If the registration view was a class-based view inheriting from DRF's `GenericAPIView` (e.g. a `CreateAPIView`), the following few lines of code would be sufficient to solve this (assuming the upstream registration view is called `DefaultRegisterUserView`):

```
class RegisterUserView(DefaultRegisterUserView):
    def get_serializer_context(self):
        return {'request': self.request}

class RegisterUserSerializer(DefaultRegisterUserSerializer):
    def create(self, validated_data):
        data = validated_data.copy()
        data['registration_remote_ip'] = self.context['request'].META.get('REMOTE_ADDR')
        return super().create(data)
```
... plus the two lines in `urls.py` and `settings.py` where the view and the serializer are configured.

2.)
Also, one may consider changing the response of the registration view such that information like "user with this email exists" is not leaked. Instead, `202 Accepted` could be an appropriate status code in all cases, with the view redirecting to the password reset view if the email address is already taken, and otherwise sending the regular registration verification email.

(It would be the frontend's responsibility to react with a proper message, like "We have sent you an email with further instructions", which would be true in all cases.)

This way, one could expose a unified register+reset endpoint which acts as a general "give me access to an account with this email address" endpoint. The frontend could of course present it in different variations for registration and for password reset purposes.

I am not proposing that these endpoints be merged (that would be another interesting issue); I am rather making the point that if the registration endpoint was a class-based view, one could easily achieve the above with something like (rough sketch):

```
class RegisterUserView(DefaultRegisterUserView):
    def post(request, *args, **kwargs):
        try:
            # Try to register user as usual
            return super().post(request, *args, *kwargs)
        except ValidationError as e:
            # Perform password reset if account exists
            email_error = e.message_dict.get('email')
            if email_error and email_error.endswith(' already exists.'):
                return PasswortResetView.as_view()(request)

            # For other errors, continue as usual
            raise e
```

**Comment by apragacz** [comment]
@peterthomassen 
Sorry to respond so late. At first I didn't like this idea, as I think about Django View Classes as an uneccesary Javaification (aka "everything has to be a class"). On the other hand, I see this as a predominant pattern of extending the views in Django community, instead of function composability.
So it could definetely improve the extensibility in more advanced cases for average Django user. Therefore I decided that we should go for it, but in the next semi-major release (probably `0.6.0` as the current one is `0.5.0`).

I think I would still leave the view functions, but they would be derived automatically from specific view class (which could be set in the settings dict - this way one does not have to fork the repository but he/she can replace specific view class in settings).

Do you agree?

**Comment by peterthomassen** [comment]
yep, that sounds very good to me!

(I disagree on the Javaification argument. My point is not that it should be a class; that just happens to be the DRF way. My point really is that this approach offers a lot of ways to hook into the view execution flow.)

**Comment by jpic** [comment]
It would also be great if we could add them to a router, so that they be documented with the rest of the endpoint.

**Comment by apragacz** [comment]
@jpic Could you explain what you mean by that? E.g. provide an example (snippet of code).

**Comment by itzmanish** [comment]
@apragacz  Actually today i was working on a project and i thought using DRR with simplejwt. But what i found is all views are function based so to extending it and modifying is really hard(I don't know if there is any other ways by which i can achieve this). So what i suggest is using of generic views so that adaption process can be much smoother and safer for production ready web application.  :)

**Comment by itzmanish** [comment]
And please do update django rest framework dependency to latest.

**Comment by apragacz** [comment]
> And please do update django rest framework dependency to latest.

This will be done in issue #70. Unfortunately it's not so simple as just bumping up the requirements.

**Comment by apragacz** [comment]
BTW: there is already a lot to do for the `0.6.0` release, so I will aim with refactoring the views for release `0.7.0`.

**Comment by apragacz** [comment]
Change will be released in next (0.8) version

**Comment by mdefeche** [comment]
@apragacz , when will version 0.8 be released ?

**Comment by apragacz** [comment]
@mdefeche I've just released it now

**Comment by mdefeche** [comment]
Thanks @apragacz  :-)
