### ISSUE TITLE
ConnectionRefusedError at /accounts/register/

### ISSUE THREAD

**Issue by vvannak** [apragacz/django-rest-registration#58]
I got an error after I register with:
username:_____
first_name:____
last_name: _____
email:__________
password:______
conf password:________

How Can I fix it?

Request Method: | POST
-- | --
http://127.0.0.1:8000/accounts/register/
2.2.1
ConnectionRefusedError
[Errno 61] Connection refused
/Users/vannak/miniconda3/lib/python3.7/socket.py in create_connection, line 716
/Users/vannak/.local/share/virtualenvs/vannak-9C9zOB6z/bin/python
3.7.0
['/Users/vannak/Desktop/authentication',  '/Users/vannak/.local/share/virtualenvs/vannak-9C9zOB6z/lib/python37.zip',  '/Users/vannak/.local/share/virtualenvs/vannak-9C9zOB6z/lib/python3.7',  '/Users/vannak/.local/share/virtualenvs/vannak-9C9zOB6z/lib/python3.7/lib-dynload',  '/Users/vannak/miniconda3/lib/python3.7',  '/Users/vannak/.local/share/virtualenvs/vannak-9C9zOB6z/lib/python3.7/site-packages']
Mon, 3 Jun 2019 15:41:53 +0000

**Comment by apragacz** [comment]
Honestly, I have no idea what could be the problem, I think I have not enough data.
* Did you test any other Django-REST-Registration endpoint?
* Do you have any other API endpoints (not from Django-REST-Registration?
* Do these other endpoints work correctly?

This looks not as a Django-REST-Registration problem, but rather a problem with Django development server (I can only assume that, because of lack of input data).
If you answered for ALL questions above 'yes', then it is a Django-REST-Registration problem (and I will need more details about your setup). If not then it is probably a general Django problem.

If it indeed is a Django problem, please follow the guidelines on how to ask for help:
https://docs.djangoproject.com/en/dev/faq/help/

**Comment by apragacz** [comment]
@vvannak any update from your side? If not I will close this issue soon.
