### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by peterthomassen** [apragacz/django-rest-registration#59]
I'd like to contribute to djange-rest-registration, but I can't manage to set up the tests. Can you please tell me how to run the test suite?

(I'll also happily create a PR to include that information somewhere in the README or docs.)

Thanks!

**Comment by apragacz** [comment]
Hi @autodiscover 
Thanks for being eager to contribute!

These are the steps to follow:

*   create virtualenv with Python 3 (3.6 is recommended). I'm using virtualenvwrapper, but it is not necessary (`python3 -m venv ...` should be ok).
*   activate virtualenv
*   install all requirements required for development

    ```
    pip install -r requirements/requirements-all.txt
    ```
*   now you can run a shell script to execute tests:

    ```
    ./scripts/run_tests.sh
    ```

    or call py.test directly:

    ```
    PYTHONPATH="." py.test
    ```
    (for some reason not providing PYTHONPATH causes problems)

Please keep in mind that we also have linters: `flake8` and `pylint`. These can be executed via:

```
./scripts/run_linters.sh
```

There is also another way to run the tests, which is by using `tox` (this is what Travis CI is using). In this case you don't need to create the virtualenv, but you will require multiple versions of Python 3 installed on your system (3.4 - 3.7). You can limit the specific cases by using the `-e` option with specific configuration (for instance, `-e py35-django21`).

BTW: If you want to put this information in README, I'd recommend to put it in `CONTRIBUTING.md` and link it in the README instead.

PS: Sorry for not responding to your issue #55. I read it and I wanted to give a comprehensive answer, but because of personal reasons I don't have time to do that. Hopefully I will be able to answer it by the end of this week.

**Comment by apragacz** [comment]
Closing as it should be done in issue #64.
