### ISSUE TITLE
Changelog location?

### ISSUE THREAD

**Issue by joshvillbrandt** [apragacz/django-rest-registration#60]
Hi, @apragacz! Do you have a changelog somewhere? I have looked on github, readthedocs, and pypi, but I can't seem to find one.

I'm interested in the changes between 0.4.3 and 0.4.5. Thanks!!!!

**Comment by apragacz** [comment]
Hi @joshvillbrandt,
there is not CHANGELOG file per se. I'm trying to document the changes on the GitHub releases tab:

https://github.com/apragacz/django-rest-registration/releases

In most cases these documented changes are the user-facing ones, I may skip the internal stuff like refactors in deeper levels.

It would be a good idea to have the information in one file, but because I'm a lazy person I would like to have a way to enter the information only once which would generate the version commit, update the CHANGELOG file, update PyPI and create appropriate version on GH releases tab.

If you strongly insist I can create the file from the current release info and keep it up to date with subsequent versions.

**Comment by joshvillbrandt** [comment]
Crap, I forgot about "releases"! This is perfect.

A minor note on usability - I'd recommend copying the commit message / saying exactly what changed instead of only referring a ticket (i.e. `Added REGISTER_VERIFICATION_ONE_TIME_USE setting` instead of `Resolved issue #44`).

Thank you!

**Comment by apragacz** [comment]
@joshvillbrandt You're right, this will make the version changes more readable. I will take that into account when releasing new versions!
