### ISSUE TITLE
Registration without username, just email and password

### ISSUE THREAD

**Issue by DataGreed** [apragacz/django-rest-registration#90]
### Is your feature request related to a problem? Please describe.
Services nowadays often do not require a username since there is no really need for it.

### Describe the solution you'd like
Enable registration with email and password only, without the need for a username.

### Describe alternatives you've considered
Writing my own solution.

**Comment by apragacz** [comment]
Hi @DataGreed,

You should be already be able to do this with Django-REST-Registration.

For instance, let's say that you have following user model (for instance in `myapp.models`):

```python
from django.contrib.auth.models import AbstractBaseUser

class SimpleEmailBasedUser(AbstractBaseUser):
    USERNAME_FIELD = 'email'
    email = models.EmailField(
        verbose_name=_("email address"),
        unique=True,
        blank=True,
    )    
```
and set it up in your settings:

```python
AUTH_USER_MODEL = 'myapp.SimpleEmailBasedUser`
```

With this setup, you should be able to have a working registration endpoints (for instance, the login endpoint would take the e-mail and password instead of username and password).

So I'm closing this one. If you encounter any specific bugs, you should report a bug report (with the specific case). I will definetely add some test cases to ensure that this scenario indeed works as expected.
